### ISSUE TITLE
CSS 高级布局技巧

### ISSUE THREAD

**Issue by sorrycc** [sorrycc/blog#14]
## 用 `:empty` 区分空元素

> 兼容性：不支持 IE8

[Demo](https://jsbin.com/rikecogamu/2/edit?html,css,output)

假如我们有以上列表：

```html
<div class="item">a</div>
<div class="item">b</div>
<div class="item"></div>
```

我们希望可以对空元素和非空元素区别处理，那么有两种方案。

用 `:empty` 选择空元素：

```css
.item:empty {
  display: none;
}
```

或者用 `:not(:empty)` 选择非空元素：

```css
.item:not(:empty) {
  border: 1px solid #ccc;
  /* ... */
}
```

## 用 `:*-Of-Type` 选择元素

> 兼容性：不支持 IE8

举例说明。

给第一个 p 段落加粗：

```css
p:first-of-type {
  font-weight: bold;
}
```

给最后一个 img 加边框：

```css
img:last-of-type {
  border: 10px solid #ccc;
}
```

给无相连的 blockquote 加样式：

```css
blockquote:only-of-type {
  border-left: 5px solid #ccc;
  padding-left: 2em;
}
```

让奇数列的 p 段落先死红色：

```css
p:nth-of-type(even) {
  color: red;
}
```

此外，`:nth-of-type` 还可以有其他类型的参数：

```css
/* 偶数个 */
:nth-of-type(even)

/* only 第三个 */
:nth-of-type(3)

/* 每第三个 */
:nth-of-type(3n)

/* 每第四加三个，即 3, 7, 11, ... */
:nth-of-type(4n+3)
```

## 用 `calc` 做流式布局

> 兼容性：不支持 IE8

[Demo](https://output.jsbin.com/rajazobeka/3)

左中右的流式布局：

```css
nav {
  position: fixed;
  left: 0;
  top: 0;
  width: 5rem;
  height: 100%;
}

aside {
  position: fixed;
  right: 0;
  top: 0;
  width: 20rem;
  height: 100%;
}

main {
  margin-left: 5rem;
  width: calc(100% - 25rem);
}
```

## 用 `vw` 和 `vh` 做全屏滚动效果

> 兼容性：不支持 IE8

[Demo](https://output.jsbin.com/doridehewe/1)

`vw` 和 `vh` 是相对于 viewport 而言的，所以不会随内容和布局的变化而变。

```css
section {
  width: 100vw;
  height: 100vh;
  
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  
  background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
}

section:nth-of-type(1) {
  background-image: url('https://unsplash.it/1024/683?image=1068');
}
section:nth-of-type(2) {
  background-image: url('https://unsplash.it/1024/683?image=1073');
}
section:nth-of-type(3) {
  background-image: url('https://unsplash.it/1024/683?image=1047');
}
section:nth-of-type(4) {
  background-image: url('https://unsplash.it/1024/683?image=1032');
}

body {
  margin: 0;
}
p {
  color: #fff;
  font-size: 100px;
  font-family: monospace;
}
```

## 用 `unset` 做 CSS Reset

> 兼容性：不支持 IE

[Demo](https://jsbin.com/titugibebu/3)

```css
body {
  color: red;
}
button {
  color: white;
  border: 1px solid #ccc;
}

/* 取消 section 中 button 的 color 设置 */
section button {
  color: unset;
}
```

## 用 `column` 做响应式的列布局

> 兼容性：不支持 IE9

[Demo](https://jsbin.com/xaruzuratu/2)

```css
nav {
  column-count: 4;
  column-width: 150px;
  column-gap: 3rem;
  column-rule: 1px dashed #ccc;
  column-fill: auto;
}

h2 {
  column-span: all;
}
```

(完)

**Comment by luobotang** [comment]
学习了！

**Comment by delkaka** [comment]
不知不觉， IE8 也逐渐退出舞台了，感觉IE6还是昨天

**Comment by xinghunMeng** [comment]
mark

**Comment by ascoders** [comment]
## 用 all + unset 做 CSS Reset

> 兼容性：不支持 IE

```css
section button {
    all: unset;
}
```

**Comment by MichealWayne** [comment]
已收，可惜calc、vw、vh等一些属性需要安卓4.4以上，还是没能用上

**Comment by yuanxj1024** [comment]
如今是等待安卓低版本系统淘汰-_-~

**Comment by Demy-ouyang** [comment]
非常棒的分享，提示一下有错别字哦，（让奇数列的 p 段落**先死**红色）显示。。。

**Comment by sorrycc** [comment]
@Demy-ouyang 感谢提醒，已修正。

**Comment by amowu** [comment]
egghead 的 [Learn Advanced CSS Layout Techniques](https://egghead.io/courses/learn-advanced-css-layout-techniques)？

**Comment by llxiang99** [comment]
get~ 学习了

**Comment by jstf9673** [comment]
mark

**Comment by JohnnieFucker** [comment]
calc 应该慎用，特别是在一些列表里。性能很差的。

**Comment by zhiqiang21** [comment]
很多属性移动端支持的都不好呀

**Comment by shfshanyue** [comment]
### 让无内容的 a 标签显示其 href
``` css
a:empty::after {
  content: attr(href);
}
```
